### ISSUE TITLE
Inadequate Logging Statements and Error Handling in EVMIndexerService

### ISSUE THREAD

**Issue by blockReal** [SigmaGmbH/swisstronik-evm-module#7]
1. **Bug/Vulnerability Description**: The EVMIndexerService lacks appropriate logging statements and proper error handling, leading to difficulties in understanding code execution and inadequate management of potential errors.

2. **Hardware and Software Specifications**: The bug was observed in a Docker environment, but specific details about hardware, operating system, Go version, Rust version, and SGX version (if applicable) are not provided.

3. **Steps to Reproduce**: Unfortunately, the bug report does not include specific steps to reproduce the issue. A detailed set of steps to trigger the bug is essential for developers to isolate and fix the problem effectively.

4. **Impact Analysis**: Inadequate logging and error handling can hinder the team's ability to track down and resolve issues promptly. It may lead to unidentified errors, making it challenging to maintain a reliable and stable EVMIndexerService.

5. **Code Fix Submission**:
   - **Code Improvement 1 - Logging Statements**: Add appropriate logging statements at crucial points within the EVMIndexerService code. Utilize log levels such as `Debug`, `Info`, `Warning`, and `Error` to provide accurate information about the significance of log messages. Example:

   ```go
   import "github.com/tendermint/log"

   // ...

   func (eis *EVMIndexerService) OnStart() error {
       // ...
       log.Info("EVMIndexerService started")
       // ...
   }
   ```

   - **Code Improvement 2 - Error Handling in RPC Calls**: When making RPC calls to the tendermint client or other operations that might result in errors, ensure that error handling is done appropriately. Use the `if err != nil` statement to check for errors and take appropriate actions based on the error conditions. Example:

   ```go
   func (eis *EVMIndexerService) OnStart() error {
       ctx := context.Background()
       status, err := eis.client.Status(ctx)
       if err != nil {
           return fmt.Errorf("failed to get status: %w", err)
       }
       // ...
   }
   ```

   - **Code Improvement 3 - Graceful Service Shutdown**: Add an `OnStop()` function to the EVMIndexerService to implement proper shutdown logic. Make sure to notify the service to stop correctly and clean up any necessary resources. Example:

   ```go
   func (eis *EVMIndexerService) OnStop() {
       log.Info("EVMIndexerService stopped")
       // Perform resource cleanup or any other necessary actions when stopping
   }
   ```

6. **Labels and Additional Context**: The bug report is specific to the lack of logging statements and error handling in the EVMIndexerService. Additional context about the impact and urgency of the issue within the project would be helpful to prioritize and address the bug appropriately.

7. **Bug Severity and Priority**: Assign an appropriate severity and priority level to the bug based on its impact and urgency. This will help the project team allocate appropriate resources and attention to address the bug.

**Comment by MikkySnow** [comment]
Hello, thanks for submitting your issue. For, sure, we will put more logs, if we will face some issues with indexer service, but for now, there is no such need
